#!/usr/bin/env bash
# bwallet.space (this repo's site/) follows bwalletx.com (/Volumes/2026/Projects/bwalletx-site), which is the master.
# bwallet.space is the App Store / Google Play app, plain bWallet (owner, 4 Oct 2026), so:
#   - shared assets (styles, scripts, images, media) are copied as they are;
#   - the home page is generated by scripts/store-site.py: branded bWallet, trading / token rooms / social
#     sign-in removed, with clear links to bwalletx.com;
#   - bWalletX-only pages (/features, /friends, /android, /extension, /developers) and /download/* redirect
#     to bwalletx.com (site/vercel.json).
# Never copied (bwallet.space-only): api/, lib/, test/, .well-known/, pair.html, social.html, vercel.json,
# package files, privacy.html (the store app's privacy URL), and the plain-b logo, icons and share images
# (logo.svg, favicon.*, icon-*.png, apple-touch-icon.png, og*.png).
#   bash scripts/sync-site.sh   then deploy: (cd site && vercel --prod)
set -euo pipefail
SRC="${BWALLETX_SITE:-/Volumes/2026/Projects/bwalletx-site}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$ROOT/site"
rsync -a \
  --exclude='.git' --exclude='.vercel' --exclude='node_modules' --exclude='.DS_Store' --exclude='media-src/' --exclude='download/' \
  --exclude='vercel.json' --exclude='privacy.html' --exclude='.gitignore' --exclude='logo.svg' --exclude='*.html' \
  --exclude='connect.js' --exclude='og-*.png' --exclude='og.png' --exclude='favicon.*' --exclude='icon-*.png' \
  --exclude='apple-touch-icon.png' \
  --include='*.css' --include='*.js' --include='*.png' --include='*.svg' --include='*.ico' \
  --include='*.webmanifest' --include='*.jpg' --include='*.mp4' --include='*.webm' --include='*.webp' \
  --include='*/' --exclude='*' \
  "$SRC/" "$DST/"
python3 "$ROOT/scripts/store-site.py" "$SRC/index.html" "$DST/index.html"
echo "synced $SRC → $DST (bWallet store edition)"
